### ISSUE TITLE
Dropdown widgets aren't styled like in the notebook

### ISSUE THREAD

**Issue by ngoldbaum** [oreillymedia/thebe#64]
Here's a simple thebe example that creates a cell with a dropdown widget:

https://gist.github.com/6086adeab1622489b31f

When I run it in chrome using an IPython 4.0 notebook server, latest ipywidgest, and notebook from the git master branch, I get something that looks like this:

![image](https://cloud.githubusercontent.com/assets/3126246/10474866/ffcf7506-7201-11e5-94f2-62f7871a8fc2.png)

Is this the intended behavior or just some breakage from moving to IPython 4.0?

**Comment by zischwartz** [comment]
Well, Thebe doesn't really include the notebook css. Which isn't a problem for the most part. But the issue here is [this line in ipywidgets](https://github.com/ipython/ipywidgets/blob/master/ipywidgets/static/notebook/js/extension.js#L74).

I think you could probably fix it by including https://cdn.rawgit.com/oreillymedia/thebe/widgetcss/static/thebe/widgets.min.css in your html.

But eventually, when things calm down, it'd be good to have better way to manage css assets, for sure. Closing this for now.

**Comment by rgbkrk** [comment]
As of this PR, ipywidgets is fully decoupled (https://github.com/ipython/ipywidgets/pull/193). Would be good to have some eyes on in checking out the PR.
